---
- name: "Pre-initialization the environment - setting and verifying config"
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  vars_files:
    - "./vars/preinit_vars.yml"
    - "~/agof_vault.yml"
  tasks:
    - name: "FUCK YOU BANDINI0"
      ansible.builtin.debug:
        msg: "#{{ automation_hub_token }}#"

    - name: "FUCK YOU BANDINI0-A"
      ansible.builtin.debug:
        msg: "#{{ automation_hub_token_vault }}#"

    - name: "Get ansible vault"
      ansible.builtin.shell:
        cat ~/agof_vault.yml
      register: av

    - name: "FUCK YOU BANDINI vault"
      ansible.builtin.debug:
        msg: "{{ av.stdout }}"

    - name: "Write ansible.cfg"
      ansible.builtin.template:
        src: ansible.cfg.j2
        dest: '../ansible.cfg'
        mode: '0600'

    - name: Check if offline token is older than 30 days
      ansible.builtin.import_tasks: jwt_check.yml
      vars:
        local_token_name: "offline_token"
        local_token: "{{ offline_token }}"
      failed_when: false
      when:
        - offline_token is defined

    - name: Check if automation_hub_token is older than 30 days
      ansible.builtin.import_tasks: jwt_check.yml
      vars:
        local_token_name: "automation_hub_token"
        local_token: "{{ automation_hub_token }}"
      failed_when: false
      when:
        - automation_hub_token is defined

    - name: "Install collections for ansible environment {{ 'forcefully' if init_env_collection_install_force }}"
      when: init_env_collection_install
      block:
        - name: "Install local patched files"
          ansible.builtin.command:
            cmd: "ansible-galaxy collection install {{ '--force' if init_env_collection_install_force }} -p '{{ ansible_cfg_patch_collection_dir }}' '{{ item }}'"
            chdir: ".."
          loop: '{{ special_collection_installs }}'

        - name: "FUCK YOU BANDINI"
          ansible.builtin.debug:
            msg: "{{ automation_hub_token }}"

        - name: "Get ansible cfg"
          ansible.builtin.shell:
            cat ../ansible.cfg
          register: cfg

        - name: "FUCK YOU BANDINI 2"
          ansible.builtin.debug:
            msg: "{{ cfg.stdout }}"

        - name: "Get overrides cfg"
          ansible.builtin.shell:
            cat ~/agof_overrides.yml
          register: cfg

        - name: "Install requirements file based collections {{ 'forcefully' if init_env_collection_install_force }}"
          ansible.builtin.command:
            cmd: |-
              ansible-galaxy collection install {{ '--force' if init_env_collection_install_force }} -p '{{ ansible_cfg_patch_collection_dir }}' -r requirements.yml
            chdir: ".."
          environment:
            ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_CERTIFIED_TOKEN: "{{ automation_hub_token }}"
            ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_VALIDATED_TOKEN: "{{ automation_hub_token }}"

    - name: "Assert that we have a valid target platform"
      ansible.builtin.assert:
        that:
          - agof_bootstrap_target | length > 0
          - agof_bootstrap_target in bootstrap_allowable_values
        fail_msg: "{{ agof_bootstrap_target }} is not a supported bootstrap target"
        success_msg: "Assertion passed: bootstrapping on {{ agof_bootstrap_target }}"

    - name: "Set our target bootstrap platform"
      ansible.builtin.set_fact:
        bootstrap_target: "{{ agof_bootstrap_target }}"
